### PR TITLE
Add support for both list and tuple coordinates.

### PR DESCRIPTION
**Pull request by lgw4**
Add support for both list and tuple coordinates.

### CODE REVIEW

**Comment by Lenka42** [comment]
@scisco This would be super useful as far as `shapely` lib returns polygons' coordinates in tuples. Merge, please.

**Comment by scisco** [comment]
I had totally missed this PR. Sorry everyone.

**Comment by scisco** [comment]
I'm still releasing it to pypi. it seems that the travis deploy is broken

**Comment by scisco** [comment]
it's updated to 1.1.1 @Lenka42 

Thanks so much @lgw4

**Pull request merged**
